"""Add username column and make phone nullable

Revision ID: 04af23d24fab
Revises: 07be93a1e1e2
Create Date: 2026-06-25 12:10:32.297962

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "04af23d24fab"
down_revision = "07be93a1e1e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(), nullable=True))
    op.alter_column("users", "phone", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("""DO $$ BEGIN
        IF EXISTS (SELECT 1 FROM users WHERE phone IS NULL) THEN
            RAISE EXCEPTION 'Cannot restore required phone numbers while phone-less users exist. Assign real verified phone numbers or retain this revision.';
        END IF;
    END $$""")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.alter_column("users", "phone", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "username")
    # ### end Alembic commands ###
