"""add courses, modules, lessons, materials, homeworks tables

Revision ID: 0843806de7ed
Revises: a1b2c3d4e5f6
Create Date: 2026-07-08 13:56:52.291681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0843806de7ed'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('preview_image', sa.String(), nullable=True),
    sa.Column('preview_video', sa.String(), nullable=True),
    sa.Column('about_teacher', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_category_id'), 'courses', ['category_id'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_teacher_id'), 'courses', ['teacher_id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_course_id'), 'modules', ['course_id'], unique=False)
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_index(op.f('ix_lessons_module_id'), 'lessons', ['module_id'], unique=False)
    op.create_table('homeworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homeworks_id'), 'homeworks', ['id'], unique=False)
    op.create_index(op.f('ix_homeworks_lesson_id'), 'homeworks', ['lesson_id'], unique=True)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_lesson_id'), 'materials', ['lesson_id'], unique=False)
    op.create_table('file_homeworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=False),
    sa.Column('deadline_days', sa.Integer(), nullable=False),
    sa.Column('file_formats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_file_size_mb', sa.Integer(), nullable=False),
    sa.Column('example_file', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['homework_id'], ['homeworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_homeworks_homework_id'), 'file_homeworks', ['homework_id'], unique=True)
    op.create_index(op.f('ix_file_homeworks_id'), 'file_homeworks', ['id'], unique=False)
    op.create_table('test_homeworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=False),
    sa.Column('timer_minutes', sa.Integer(), nullable=True),
    sa.Column('pass_ball', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homeworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_homeworks_homework_id'), 'test_homeworks', ['homework_id'], unique=True)
    op.create_index(op.f('ix_test_homeworks_id'), 'test_homeworks', ['id'], unique=False)
    op.create_table('text_homeworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=False),
    sa.Column('deadline_days', sa.Integer(), nullable=False),
    sa.Column('pass_ball', sa.Integer(), nullable=False),
    sa.Column('min_words', sa.Integer(), nullable=False),
    sa.Column('grading_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['homework_id'], ['homeworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_homeworks_homework_id'), 'text_homeworks', ['homework_id'], unique=True)
    op.create_index(op.f('ix_text_homeworks_id'), 'text_homeworks', ['id'], unique=False)
    op.create_table('test_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_homework_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ball', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_homework_id'], ['test_homeworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_questions_id'), 'test_questions', ['id'], unique=False)
    op.create_index(op.f('ix_test_questions_test_homework_id'), 'test_questions', ['test_homework_id'], unique=False)
    op.create_table('test_question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_question_options_id'), 'test_question_options', ['id'], unique=False)
    op.create_index(op.f('ix_test_question_options_question_id'), 'test_question_options', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_question_options_question_id'), table_name='test_question_options')
    op.drop_index(op.f('ix_test_question_options_id'), table_name='test_question_options')
    op.drop_table('test_question_options')
    op.drop_index(op.f('ix_test_questions_test_homework_id'), table_name='test_questions')
    op.drop_index(op.f('ix_test_questions_id'), table_name='test_questions')
    op.drop_table('test_questions')
    op.drop_index(op.f('ix_text_homeworks_id'), table_name='text_homeworks')
    op.drop_index(op.f('ix_text_homeworks_homework_id'), table_name='text_homeworks')
    op.drop_table('text_homeworks')
    op.drop_index(op.f('ix_test_homeworks_id'), table_name='test_homeworks')
    op.drop_index(op.f('ix_test_homeworks_homework_id'), table_name='test_homeworks')
    op.drop_table('test_homeworks')
    op.drop_index(op.f('ix_file_homeworks_id'), table_name='file_homeworks')
    op.drop_index(op.f('ix_file_homeworks_homework_id'), table_name='file_homeworks')
    op.drop_table('file_homeworks')
    op.drop_index(op.f('ix_materials_lesson_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_homeworks_lesson_id'), table_name='homeworks')
    op.drop_index(op.f('ix_homeworks_id'), table_name='homeworks')
    op.drop_table('homeworks')
    op.drop_index(op.f('ix_lessons_module_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_index(op.f('ix_modules_course_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_courses_teacher_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_category_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
