"""Change category name to JSONB

Revision ID: 1a3cece44193
Revises: 04af23d24fab
Create Date: 2026-06-25 12:18:20.361008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a3cece44193'
down_revision = '04af23d24fab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using="json_build_object('uz', name, 'ru', name, 'en', name)::jsonb")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="name->>'uz'")
    # ### end Alembic commands ###
