"""Add seller profile table

Revision ID: 40c1b21e0f5e
Revises: 459b5031b527
Create Date: 2026-06-25 11:06:12.133946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c1b21e0f5e'
down_revision = '459b5031b527'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('portfolio', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_profiles_id'), 'seller_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_seller_profiles_user_id'), 'seller_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seller_profiles_user_id'), table_name='seller_profiles')
    op.drop_index(op.f('ix_seller_profiles_id'), table_name='seller_profiles')
    op.drop_table('seller_profiles')
    # ### end Alembic commands ###
