"""Add password reset codes table

Revision ID: 5dd6b9efb16e
Revises: 1a3cece44193
Create Date: 2026-06-25 13:17:05.525122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd6b9efb16e'
down_revision = '1a3cece44193'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_codes_id'), 'password_reset_codes', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_codes_phone'), 'password_reset_codes', ['phone'], unique=False)
    op.create_index(op.f('ix_password_reset_codes_token'), 'password_reset_codes', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_codes_token'), table_name='password_reset_codes')
    op.drop_index(op.f('ix_password_reset_codes_phone'), table_name='password_reset_codes')
    op.drop_index(op.f('ix_password_reset_codes_id'), table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    # ### end Alembic commands ###
